import type { MockProduct, MockRecipe } from './types';

const CDN = 'https://theteaplanet.com/cdn/shop/files';

export const MOCK_PRODUCTS: MockProduct[] = [
  /* ── SILKY MIX ── */
  {
    id: 'prod_001',
    handle: 'silky-mix-original-base',
    title: 'Silky Mix — Original Boba Base',
    subtitle: 'The all-in-one hot & cold beverage base',
    category: 'Silky Mix Bases',
    categoryHandle: 'silky-mix',
    packSizes: ['500g', '1.5 kg', '5 kg', '10 kg'],
    price: 599,
    compareAtPrice: 699,
    unit: 'per kg',
    sku: '72002',
    image: `${CDN}/TP_cafe.jpg`,
    tags: ['silky-mix', 'premix', 'bestseller', 'hot', 'cold'],
    badge: 'Best Seller',
    isBestSeller: true,
    description:
      'The professional-grade boba base trusted by 100+ partners. Works hot or cold — one SKU, unlimited recipes. Cost per cup from ₹19 vs ₹22–25 for imported alternatives.',
    benefits: [
      'Hot & cold — one SKU replaces 3–4 separate ingredients',
      'Cost per cup: ₹19–20 (vs ₹22–25 imported)',
      '3x higher repeat rate vs generic premixes',
      'FSSC 22000 certified manufacturing',
      '1-week dispatch vs 4–8 weeks for imports',
    ],
    usageDosage: {
      hot:   '10–15g per 100ml hot water or milk',
      cold:  '30g per 350ml cold milk or water',
      notes: 'Adjust sweetness by varying dosage. Best paired with Tapioca Pearls (SKU 17025).',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Hotel & Resort', 'Distributor'],
    faq: [
      { q: 'What is the shelf life?',        a: '18 months from manufacturing date in original sealed packaging.' },
      { q: 'Does it need refrigeration?',    a: 'No — store cool and dry. Refrigerate after opening.' },
      { q: 'Is it vegetarian / vegan?',      a: 'Yes — fully plant-based, no animal derivatives.' },
      { q: 'What is the minimum order?',     a: 'Retail: 500g. Bulk B2B: 5 kg. Custom pack sizes on request.' },
      { q: 'How fast do you dispatch?',      a: '48-hour dispatch on standard orders. 1-week for bulk/custom.' },
    ],
    relatedRecipes: ['classic-boba-milk-tea', 'brown-sugar-boba', 'thai-milk-tea'],
    crossSell: ['tapioca-pearls-black', 'popping-boba-strawberry', 'brown-sugar-syrup'],
  },

  /* ── TAPIOCA PEARLS ── */
  {
    id: 'prod_002',
    handle: 'tapioca-pearls-black',
    title: 'Tapioca Pearls — Black (Quick-Cook)',
    subtitle: 'Ready in 5 minutes. Consistent chew every batch.',
    category: 'Tapioca Pearls',
    categoryHandle: 'tapioca-pearls',
    packSizes: ['1 kg', '5 kg', '10 kg'],
    price: 320,
    unit: 'per kg',
    sku: '17025',
    image: `${CDN}/Boba_packs.jpg`,
    tags: ['boba', 'topping', 'bestseller'],
    badge: 'Best Seller',
    isBestSeller: true,
    description:
      'Pre-cooked quick-cook tapioca pearls with consistent chew texture. Cook in 5 minutes vs 30 for raw pearls. Reduces kitchen prep and waste.',
    benefits: [
      '5-minute cook time vs 30 mins for raw pearls',
      'Consistent chew texture batch after batch',
      'Brown sugar infused variant available',
      'Stays fresh in sugar syrup for 4 hours',
      'Reduces kitchen prep time by 80%',
    ],
    usageDosage: {
      notes: 'Boil in water 5 minutes, drain, coat in brown sugar syrup. Serve within 4 hours.',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Fine Dining'],
    faq: [
      { q: 'How long do cooked pearls last?',  a: 'Up to 4 hours in brown sugar syrup at room temperature.' },
      { q: 'Standard vs instant — difference?', a: 'Standard: 5 min cook, better texture. Instant: 30 sec, ideal for fast QSR.' },
    ],
    relatedRecipes: ['classic-boba-milk-tea', 'brown-sugar-boba', 'thai-milk-tea'],
    crossSell: ['silky-mix-original-base', 'brown-sugar-syrup', 'popping-boba-strawberry'],
  },

  /* ── POPPING BOBA ── */
  {
    id: 'prod_003',
    handle: 'popping-boba-strawberry',
    title: 'Popping Boba — Strawberry',
    subtitle: 'Juice-filled bursting pearls. No cooking. Premium upsell.',
    category: 'Popping Boba',
    categoryHandle: 'popping-boba',
    packSizes: ['450g', '3.2 kg'],
    price: 480,
    unit: 'per 450g',
    sku: 'PB-STR-001',
    image: `${CDN}/Boba_packs.jpg`,
    tags: ['popping-boba', 'topping', 'new'],
    badge: 'New',
    isNew: true,
    description:
      'Real juice-filled popping boba that bursts in the mouth. No cooking required. Adds ₹30–50 to your cup selling price. Available in 6+ varieties.',
    benefits: [
      'No cooking — open and serve',
      'Real fruit juice filling',
      'Premium upsell: +₹30–50 per cup',
      '6+ flavours: Strawberry, Mango, Passion Fruit, Lychee, Blueberry, Green Apple',
      '18-month shelf life',
    ],
    usageDosage: {
      notes: 'Drain from storage liquid, rinse. Add 2–3 tbsp per cup. No heating required.',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Fine Dining', 'Dessert Shops'],
    faq: [
      { q: 'Do these need cooking?',     a: 'No — ready to use. Drain and rinse from container.' },
      { q: 'What flavours are in stock?', a: 'Strawberry, Mango, Passion Fruit, Lychee, Blueberry, Green Apple.' },
    ],
    relatedRecipes: ['iced-taro-boba', 'sparkling-kaffir-lime'],
    crossSell: ['silky-mix-original-base', 'tapioca-pearls-black', 'nata-de-coco'],
  },

  /* ── BROWN SUGAR SYRUP ── */
  {
    id: 'prod_004',
    handle: 'brown-sugar-syrup',
    title: 'Brown Sugar Syrup',
    subtitle: 'Thick, rich, Taiwanese-style caramel syrup',
    category: 'Syrups & Concentrates',
    categoryHandle: 'syrups-concentrates',
    packSizes: ['500ml', '1L', '5L'],
    price: 280,
    unit: 'per 500ml',
    sku: '91171',
    image: `${CDN}/TP_cafe.jpg`,
    tags: ['syrup', 'bestseller'],
    isBestSeller: true,
    description:
      'Authentic Taiwanese-style brown sugar syrup. Thick and consistent for tiger stripes, drizzle, and mixing. Heat stable to 100°C.',
    benefits: [
      'Thick consistency — ideal for tiger stripes & drizzle',
      'Authentic caramel depth with molasses notes',
      'Heat stable up to 100°C',
      'Cost per cup: ₹5–8',
    ],
    usageDosage: {
      hot:  '15–20ml per 100ml serving',
      cold: '20–30ml per 350ml serving',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Bakery & Dessert'],
    faq: [
      { q: 'Suitable for cake drizzle?', a: 'Yes — thick consistency works well for decoration.' },
    ],
    relatedRecipes: ['brown-sugar-boba', 'classic-boba-milk-tea'],
    crossSell: ['tapioca-pearls-black', 'silky-mix-original-base'],
  },

  /* ── SPONGE CAKE MIXES ── */
  {
    id: 'prod_005',
    handle: 'sponge-cake-mix-spiced-chai',
    title: 'Sponge Cake Base Mix — Spiced Chai',
    subtitle: 'Professional chiffon sponge with authentic chai flavour',
    category: 'Sponge Cake Base Mixes',
    categoryHandle: 'sponge-cake-mixes',
    packSizes: ['500g'],
    price: 899,
    unit: 'per pack',
    sku: 'SCM-CHAI-001',
    image: `${CDN}/SpicedChai.jpg`,
    tags: ['cake', 'dessert', 'new'],
    badge: 'New',
    isNew: true,
    description:
      'Professional chiffon sponge cake base with authentic Indian spiced chai flavour. Pairs perfectly with boba toppings and boosts dessert menu revenue.',
    benefits: [
      'Consistent bakery-quality results every time',
      'Pairs with boba toppings for premium desserts',
      'Extends your menu into desserts & cakes',
      'No specialist baking skills required',
    ],
    usageDosage: {
      notes: 'Mix 500g with eggs, oil, water per pack instructions. Bake at 170°C for 25–30 minutes.',
    },
    applications: ['Bakery & Dessert Shop', 'Café & Tea Bar', 'Cloud Kitchen', 'Fine Dining'],
    faq: [
      { q: 'What toppings work best?', a: 'Boba pearls, popping boba, nata de coco, and konjac jelly all work beautifully.' },
      { q: 'Other flavours available?', a: 'Yes: Matcha Tea, Jasmine Green Tea, Earl Grey, Black Tea.' },
    ],
    relatedRecipes: ['matcha-boba-sponge-cake'],
    crossSell: ['tapioca-pearls-black', 'popping-boba-strawberry', 'nata-de-coco'],
  },
  {
    id: 'prod_006',
    handle: 'sponge-cake-mix-matcha',
    title: 'Sponge Cake Base Mix — Matcha Tea',
    subtitle: 'Premium Japanese matcha chiffon sponge base',
    category: 'Sponge Cake Base Mixes',
    categoryHandle: 'sponge-cake-mixes',
    packSizes: ['500g'],
    price: 899,
    unit: 'per pack',
    sku: 'SCM-MATCHA-001',
    image: `${CDN}/MatchaTea.jpg`,
    tags: ['cake', 'dessert', 'matcha'],
    description: 'Premium matcha chiffon sponge cake base with authentic Japanese green tea flavour. Perfect for boba cheesecake menus.',
    benefits: [
      'Authentic matcha colour and flavour',
      'Pairs with taro and red bean toppings',
      'Instagram-worthy deep green colour',
    ],
    usageDosage: { notes: 'Mix per pack instructions. Bake at 170°C for 25–30 minutes.' },
    applications: ['Bakery & Dessert Shop', 'Café & Tea Bar'],
    faq: [{ q: 'Can I add boba toppings?', a: 'Yes — matcha sponge pairs beautifully with popping boba and tapioca.' }],
    relatedRecipes: ['matcha-boba-sponge-cake'],
    crossSell: ['tapioca-pearls-black', 'popping-boba-strawberry'],
  },
];

export const MOCK_RECIPES: MockRecipe[] = [
  {
    slug: 'classic-boba-milk-tea',
    title: 'Classic Boba Milk Tea',
    category: 'Milk Teas',
    prepTime: '8 min',
    servingSize: '350ml',
    difficulty: 'Easy',
    image: `${CDN}/TP_cafe.jpg`,
    description: 'The original boba milk tea. Consistent, crowd-pleasing, and highly profitable. The backbone of any boba menu.',
    ingredients: [
      { name: 'Silky Mix — Original Base', dosage: '30g',        sku: '72002', productHandle: 'silky-mix-original-base' },
      { name: 'Black Tapioca Pearls (cooked)', dosage: '50g',    sku: '17025', productHandle: 'tapioca-pearls-black' },
      { name: 'Cold Milk or Water',        dosage: '280ml' },
      { name: 'Ice',                       dosage: '100g' },
    ],
    steps: [
      'Cook tapioca pearls: boil 5 minutes, drain, coat in brown sugar syrup.',
      'Add 30g Silky Mix to shaker.',
      'Add 280ml cold milk and 100g ice.',
      'Shake vigorously 15 seconds until frothy.',
      'Add cooked pearls to serving cup.',
      'Pour shaken mixture over pearls.',
      'Serve with wide boba straw.',
    ],
    sellingNotes: 'Cost per cup: ₹22–28. Selling price: ₹120–180. Margin: 75–85%. Upsell popping boba for +₹30.',
    applicationTypes: ['Café', 'QSR', 'Cloud Kitchen'],
    linkedProducts: ['silky-mix-original-base', 'tapioca-pearls-black', 'brown-sugar-syrup'],
  },
  {
    slug: 'brown-sugar-boba',
    title: 'Brown Sugar Tiger Boba',
    category: 'Signature Fusions',
    prepTime: '10 min',
    servingSize: '350ml',
    difficulty: 'Medium',
    image: `${CDN}/TP_cafe.jpg`,
    description: 'The viral tiger-stripe boba that drives social media shares and repeat visits. Instagram-worthy every time.',
    ingredients: [
      { name: 'Silky Mix — Original Base', dosage: '30g',     sku: '72002', productHandle: 'silky-mix-original-base' },
      { name: 'Black Tapioca Pearls (cooked)', dosage: '60g', sku: '17025', productHandle: 'tapioca-pearls-black' },
      { name: 'Brown Sugar Syrup',         dosage: '25ml',    sku: '91171', productHandle: 'brown-sugar-syrup' },
      { name: 'Fresh Milk',                dosage: '280ml' },
      { name: 'Ice',                       dosage: '100g' },
    ],
    steps: [
      'Cook pearls and coat in brown sugar syrup while hot.',
      'Drizzle brown sugar syrup inside glass in tiger stripe pattern.',
      'Add hot coated pearls immediately.',
      'Fill glass with ice.',
      'Shake Silky Mix with milk and pour slowly over ice.',
      'Serve immediately for maximum visual impact.',
    ],
    sellingNotes: 'Cost per cup: ₹28–35. Selling price: ₹150–220. High Instagram-ability — encourage photo sharing.',
    applicationTypes: ['Café', 'Fine Dining', 'QSR'],
    linkedProducts: ['silky-mix-original-base', 'tapioca-pearls-black', 'brown-sugar-syrup'],
  },
  {
    slug: 'thai-milk-tea',
    title: 'Thai Milk Tea',
    category: 'Milk Teas',
    prepTime: '8 min',
    servingSize: '350ml',
    difficulty: 'Easy',
    image: `${CDN}/TP_cafe.jpg`,
    description: 'Aromatic Thai tea with condensed milk and tapioca. A café classic with strong repeat purchase behaviour.',
    ingredients: [
      { name: 'Thai Tea Concentrate',      dosage: '80ml' },
      { name: 'Condensed Milk',            dosage: '30ml' },
      { name: 'Black Tapioca Pearls (cooked)', dosage: '50g', sku: '17025', productHandle: 'tapioca-pearls-black' },
      { name: 'Ice',                       dosage: '150g' },
    ],
    steps: [
      'Brew Thai tea concentrate or use pre-made.',
      'Add condensed milk and stir.',
      'Add cooked tapioca pearls to cup.',
      'Fill with ice and pour tea mixture.',
      'Serve with boba straw.',
    ],
    sellingNotes: 'Cost per cup: ₹18–24. Selling price: ₹100–160. Strong repeat purchase. Pair with popping boba upsell.',
    applicationTypes: ['Café', 'QSR', 'Cloud Kitchen'],
    linkedProducts: ['tapioca-pearls-black', 'brown-sugar-syrup'],
  },
  {
    slug: 'sparkling-kaffir-lime',
    title: 'Sparkling Kaffir Lime',
    category: 'Fruit Coolers',
    prepTime: '5 min',
    servingSize: '350ml',
    difficulty: 'Easy',
    image: `${CDN}/TP_cafe.jpg`,
    description: 'Zesty kaffir lime with a sparkling finish. Tropical and bold. A seasonal bestseller with high margin.',
    ingredients: [
      { name: 'Kaffir Lime Syrup',         dosage: '30ml' },
      { name: 'Popping Boba — any flavour', dosage: '40g', productHandle: 'popping-boba-strawberry' },
      { name: 'Sparkling Water',           dosage: '280ml' },
      { name: 'Ice',                       dosage: '100g' },
      { name: 'Kaffir Lime Leaf (garnish)', dosage: '1 leaf' },
    ],
    steps: [
      'Add popping boba to serving glass.',
      'Add ice.',
      'Mix kaffir lime syrup with sparkling water.',
      'Pour over ice slowly.',
      'Garnish with fresh kaffir lime leaf.',
    ],
    sellingNotes: 'Cost per cup: ₹15–20. Selling price: ₹140–180. No cooking, fast service. Premium look.',
    applicationTypes: ['Café', 'Fine Dining', 'Cloud Kitchen'],
    linkedProducts: ['popping-boba-strawberry'],
  },
];

export const SIGNATURE_DRINKS = {
  fusion: [
    { title: 'Mocha & Boba',           desc: 'Rich espresso meets creamy milk tea. Topped with signature popping boba.',       image: `${CDN}/TP_cafe.jpg`, recipe: 'mocha-boba' },
    { title: 'Taro & Matcha',          desc: 'Earthy matcha blended with creamy taro. A premium fusion favourite.',              image: `${CDN}/TP_cafe.jpg`, recipe: 'taro-matcha' },
    { title: 'Thai Milk Tea',          desc: 'Aromatic Thai tea with condensed milk and tapioca. A café classic.',               image: `${CDN}/TP_cafe.jpg`, recipe: 'thai-milk-tea' },
    { title: 'Brown Tiger Sugar Latte',desc: 'Silky latte with caramelised brown sugar drizzle. Instagram-worthy every time.',  image: `${CDN}/TP_cafe.jpg`, recipe: 'brown-sugar-boba' },
  ],
  coolers: [
    { title: 'Sparkling Kaffir Lime',  desc: 'Zesty kaffir lime with a sparkling finish. Tropical and bold.',                   image: `${CDN}/TP_cafe.jpg`, recipe: 'sparkling-kaffir-lime' },
    { title: 'Yuzu Green Tea',         desc: 'Bright yuzu citrus with delicate green tea. Light, refreshing, premium.',          image: `${CDN}/TP_cafe.jpg`, recipe: 'yuzu-green-tea' },
    { title: 'Ginger Jasmine',         desc: 'Warming ginger spice with floral jasmine. Wellness-focused favourite.',            image: `${CDN}/TP_cafe.jpg`, recipe: 'ginger-jasmine' },
    { title: 'Oolong with Tapioca',    desc: 'Smooth oolong base with chewy tapioca pearls. A timeless combination.',            image: `${CDN}/TP_cafe.jpg`, recipe: 'oolong-tapioca' },
  ],
};

export const SPONGE_CAKE_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'sponge-cake-mixes');
export const BEST_SELLERS       = MOCK_PRODUCTS.filter((p) => p.isBestSeller);
export const MOCK_COLLECTIONS = [
  { handle: 'boba-innovations',    title: 'Boba Innovations',      description: 'Complete boba ingredient range.',               products: MOCK_PRODUCTS.filter((p) => ['tapioca-pearls','popping-boba'].includes(p.categoryHandle)) },
  { handle: 'syrups-concentrates', title: 'Syrups & Concentrates', description: 'Professional flavour syrups. 25+ flavours.',    products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'syrups-concentrates') },
  { handle: 'silky-mix',           title: 'Silky Mix Bases',       description: 'All-in-one hot & cold beverage bases.',         products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'silky-mix') },
  { handle: 'sponge-cake-mixes',   title: 'Sponge Cake Base Mixes',description: 'Professional chiffon sponge cake bases.',       products: SPONGE_CAKE_PRODUCTS },
  { handle: 'tapioca-pearls',      title: 'Tapioca Pearls',        description: 'Standard & instant tapioca pearls.',            products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'tapioca-pearls') },
  { handle: 'popping-boba',        title: 'Popping Boba',          description: 'Juice-filled bursting pearls. 6+ varieties.',   products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'popping-boba') },
];
