import type { MockProduct, MockRecipe } from './types';

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: 'prod_001',
    handle: 'silky-mix-original-base',
    title: 'Silky Mix — Original Boba Base',
    subtitle: 'The all-in-one hot & cold beverage base',
    category: 'Boba Innovations',
    categoryHandle: 'boba-innovations',
    packSizes: ['500g', '1 kg', '5 kg', '10 kg'],
    price: 599,
    compareAtPrice: 699,
    unit: 'per kg',
    sku: 'BI-SILKY-001',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tags: ['boba', 'premix', 'bestseller', 'hot', 'cold'],
    badge: 'Best Seller',
    isBestSeller: true,
    description: 'The professional-grade boba base trusted by 500+ cafes. Works hot or cold — one product, unlimited recipes.',
    benefits: [
      'Works for hot & cold beverages — one SKU, full menu',
      'Consistent texture every cup — no barista guesswork',
      'Cost per cup: ₹12–18 depending on recipe',
      'FSSC 22000 certified manufacturing',
      'No added preservatives',
    ],
    usageDosage: {
      hot: '10–15g per 100ml hot water or milk',
      cold: '30g per 350ml cold milk or water',
      notes: 'Adjust sweetness by varying dosage. Best paired with Tapioca Pearls and Popping Boba.',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Hotel & Resort', 'Distributor / Reseller'],
    faq: [
      { q: 'What is the shelf life?', a: '18 months from manufacturing date in original sealed packaging.' },
      { q: 'Does it need refrigeration?', a: 'No — store in a cool, dry place. Refrigerate after opening.' },
      { q: 'Is it vegetarian / vegan?', a: 'Yes — fully plant-based, no animal derivatives.' },
      { q: 'What\'s the minimum order quantity?', a: 'Retail: 500g. Bulk / B2B: 5 kg minimum. Custom pack sizes available on request.' },
    ],
    relatedRecipes: ['classic-boba-milk-tea', 'iced-taro-boba', 'brown-sugar-boba'],
    crossSell: ['tapioca-pearls-black', 'popping-boba-strawberry', 'brown-sugar-syrup'],
  },
  {
    id: 'prod_002',
    handle: 'tapioca-pearls-black',
    title: 'Tapioca Pearls — Black (Ready-Cook)',
    subtitle: 'Chewy boba pearls, ready in 5 minutes',
    category: 'Boba Innovations',
    categoryHandle: 'boba-innovations',
    packSizes: ['1 kg', '5 kg', '10 kg'],
    price: 320,
    unit: 'per kg',
    sku: 'BI-TAPIO-001',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tags: ['boba', 'topping', 'bestseller'],
    badge: 'Best Seller',
    isBestSeller: true,
    description: 'Pre-cooked, quick-cook tapioca pearls with consistent chew texture. Cook in 5 minutes vs 30 for raw pearls.',
    benefits: [
      '5-minute cook time vs 30 for raw pearls',
      'Consistent chew texture batch after batch',
      'Brown sugar infused variant available',
      'Stays fresh in sugar syrup for 4 hours',
    ],
    usageDosage: {
      notes: 'Boil in water for 5 minutes, drain, coat in brown sugar syrup. Serve within 4 hours.',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Fine Dining'],
    faq: [
      { q: 'How long do cooked pearls last?', a: 'Up to 4 hours in brown sugar syrup at room temperature.' },
      { q: 'Are these the same as boba pearls?', a: 'Yes — boba, tapioca pearls, and bubble tea pearls are the same thing.' },
    ],
    relatedRecipes: ['classic-boba-milk-tea', 'brown-sugar-boba'],
    crossSell: ['silky-mix-original-base', 'brown-sugar-syrup', 'popping-boba-strawberry'],
  },
  {
    id: 'prod_003',
    handle: 'popping-boba-strawberry',
    title: 'Popping Boba — Strawberry',
    subtitle: 'Juice-filled bursting pearls for instant wow',
    category: 'Boba Innovations',
    categoryHandle: 'boba-innovations',
    packSizes: ['450g', '3.2 kg'],
    price: 480,
    unit: 'per 450g',
    sku: 'BI-POPB-STR-001',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tags: ['boba', 'topping', 'new'],
    badge: 'New',
    isNew: true,
    description: 'Real juice-filled popping boba that bursts in the mouth. No cooking required. Premium upsell ingredient.',
    benefits: [
      'No cooking required — open and serve',
      'Real fruit juice filling',
      'Premium upsell: +₹30–50 per cup',
      'Available in 10+ flavours',
      '18-month shelf life',
    ],
    usageDosage: {
      notes: 'Drain and rinse from storage liquid. Add 2–3 tbsp per cup. No heating required.',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Fine Dining', 'Dessert Shops'],
    faq: [
      { q: 'Do these need to be cooked?', a: 'No — ready to use straight from the container. Just drain and rinse.' },
      { q: 'What flavours are available?', a: 'Strawberry, Mango, Passion Fruit, Lychee, Blueberry, Green Apple and more.' },
    ],
    relatedRecipes: ['iced-taro-boba', 'fruit-tea-burst'],
    crossSell: ['silky-mix-original-base', 'tapioca-pearls-black'],
  },
  {
    id: 'prod_004',
    handle: 'brown-sugar-syrup',
    title: 'Brown Sugar Syrup',
    subtitle: 'Rich caramel-forward flavour syrup',
    category: 'Syrups & Flavours',
    categoryHandle: 'syrups-flavours',
    packSizes: ['500ml', '1L', '5L'],
    price: 280,
    unit: 'per 500ml',
    sku: 'SYR-BRNS-001',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tags: ['syrup', 'flavour', 'bestseller'],
    isBestSeller: true,
    description: 'Authentic Taiwanese-style brown sugar syrup. Thick, rich and consistent for drizzle and mixing.',
    benefits: [
      'Thick consistency — ideal for tiger stripes and drizzle',
      'Authentic caramel depth with molasses notes',
      'Heat stable up to 100°C',
      'Cost per cup: ₹5–8',
    ],
    usageDosage: {
      hot: '15–20ml per 100ml serving',
      cold: '20–30ml per 350ml serving',
    },
    applications: ['Café & Tea Bar', 'QSR', 'Cloud Kitchen', 'Bakery & Dessert'],
    faq: [
      { q: 'Is this suitable for cake drizzle?', a: 'Yes — thick consistency works well for drizzle and decoration.' },
    ],
    relatedRecipes: ['brown-sugar-boba', 'classic-boba-milk-tea'],
    crossSell: ['tapioca-pearls-black', 'silky-mix-original-base'],
  },
];

export const MOCK_RECIPES: MockRecipe[] = [
  {
    slug: 'classic-boba-milk-tea',
    title: 'Classic Boba Milk Tea',
    category: 'Boba Drinks',
    prepTime: '8 min',
    servingSize: '350ml',
    difficulty: 'Easy',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'The original boba milk tea recipe that launched a thousand menus. Consistent, crowd-pleasing, and highly profitable.',
    ingredients: [
      { name: 'Silky Mix — Original Base', dosage: '30g', sku: 'BI-SILKY-001', productHandle: 'silky-mix-original-base' },
      { name: 'Black Tapioca Pearls', dosage: '50g (cooked)', sku: 'BI-TAPIO-001', productHandle: 'tapioca-pearls-black' },
      { name: 'Cold Milk or Water', dosage: '280ml' },
      { name: 'Ice', dosage: '100g' },
    ],
    steps: [
      'Cook tapioca pearls: boil 5 minutes, drain, coat in brown sugar syrup.',
      'Add 30g Silky Mix to shaker.',
      'Add 280ml cold milk and 100g ice to shaker.',
      'Shake vigorously for 15 seconds until frothy.',
      'Add cooked pearls to serving cup.',
      'Pour shaken mixture over pearls.',
      'Serve with wide boba straw.',
    ],
    sellingNotes: 'Cost per cup: ₹22–28. Selling price: ₹120–180. Margin: 75–85%. Upsell popping boba for +₹30.',
    applicationTypes: ['Café', 'QSR', 'Cloud Kitchen'],
    linkedProducts: ['silky-mix-original-base', 'tapioca-pearls-black', 'brown-sugar-syrup'],
  },
  {
    slug: 'brown-sugar-boba',
    title: 'Brown Sugar Tiger Boba',
    category: 'Boba Drinks',
    prepTime: '10 min',
    servingSize: '350ml',
    difficulty: 'Medium',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'The viral tiger-stripe boba that drives social media shares and repeat visits.',
    ingredients: [
      { name: 'Silky Mix — Original Base', dosage: '30g', sku: 'BI-SILKY-001', productHandle: 'silky-mix-original-base' },
      { name: 'Black Tapioca Pearls', dosage: '60g (cooked)', sku: 'BI-TAPIO-001', productHandle: 'tapioca-pearls-black' },
      { name: 'Brown Sugar Syrup', dosage: '25ml', sku: 'SYR-BRNS-001', productHandle: 'brown-sugar-syrup' },
      { name: 'Fresh Milk', dosage: '280ml' },
      { name: 'Ice', dosage: '100g' },
    ],
    steps: [
      'Cook pearls and coat in brown sugar syrup while hot.',
      'Drizzle brown sugar syrup on inside of serving glass in tiger stripe pattern.',
      'Add hot coated pearls immediately.',
      'Fill glass with ice.',
      'Shake Silky Mix with milk and pour slowly over ice.',
      'Serve immediately for maximum visual impact.',
    ],
    sellingNotes: 'Cost per cup: ₹28–35. Selling price: ₹150–220. High Instagram-ability — encourage photo sharing.',
    applicationTypes: ['Café', 'Fine Dining', 'QSR'],
    linkedProducts: ['silky-mix-original-base', 'tapioca-pearls-black', 'brown-sugar-syrup'],
  },
  {
    slug: 'iced-taro-boba',
    title: 'Iced Taro Boba',
    category: 'Boba Drinks',
    prepTime: '7 min',
    servingSize: '350ml',
    difficulty: 'Easy',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Creamy, naturally purple taro boba that\'s consistently a menu bestseller.',
    ingredients: [
      { name: 'Taro Silky Mix', dosage: '30g', sku: 'BI-SILKY-TARO-001' },
      { name: 'Popping Boba — Strawberry', dosage: '40g', sku: 'BI-POPB-STR-001', productHandle: 'popping-boba-strawberry' },
      { name: 'Cold Milk', dosage: '280ml' },
      { name: 'Ice', dosage: '100g' },
    ],
    steps: [
      'Add 30g Taro Silky Mix to shaker with milk and ice.',
      'Shake vigorously for 15 seconds.',
      'Place drained popping boba in serving cup.',
      'Pour taro mixture over boba.',
      'Garnish with a few popping boba on top.',
    ],
    sellingNotes: 'Cost per cup: ₹26–32. Selling price: ₹130–180. Purple colour is highly photogenic.',
    applicationTypes: ['Café', 'QSR', 'Cloud Kitchen'],
    linkedProducts: ['popping-boba-strawberry', 'silky-mix-original-base'],
  },
];

export const MOCK_COLLECTIONS = [
  {
    handle: 'boba-innovations',
    title: 'Boba Innovations',
    description: 'Complete boba ingredient range: bases, pearls, popping boba, and toppings for your bubble tea menu.',
    products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'boba-innovations'),
  },
  {
    handle: 'syrups-flavours',
    title: 'Syrups & Flavours',
    description: 'Professional flavour syrups for beverages, desserts, and baking. 25+ flavours in stock.',
    products: MOCK_PRODUCTS.filter((p) => p.categoryHandle === 'syrups-flavours'),
  },
];

export const BEST_SELLERS = MOCK_PRODUCTS.filter((p) => p.isBestSeller);
